In [37]:
import pandas as pd
import geopandas as gpd

In [38]:
df = pd.read_excel('../data/raw_nypd_arrests_data.xlsx')
df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,K,83,0,25-44,M,WHITE HISPANIC,1002212,193214,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,104,0,25-44,M,WHITE HISPANIC,1012082,206579,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200507,F,B,52,0,25-44,M,WHITE HISPANIC,1017440,256046,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,0,25-44,F,BLACK,936722,172119,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,K,72,0,25-44,M,WHITE HISPANIC,981292,171046,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",113.0,FORGERY,PL 1702500,F,Q,104,0,18-24,M,WHITE HISPANIC,1011989,197484,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",351.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450001,M,B,40,2,25-44,M,WHITE HISPANIC,1007115,237715,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200501,F,K,79,0,45-64,M,BLACK,998729,192685,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,198.0,CRIMINAL CONTEMPT 1,126.0,MISCELLANEOUS PENAL LAW,PL 21551B4,F,Q,105,0,25-44,M,ASIAN / PACIFIC ISLANDER,1057767,203993,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,439.0,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",109.0,GRAND LARCENY,PL 1553501,F,M,18,0,45-64,M,BLACK,991531,217373,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [39]:
print(df.shape)
print(df.columns.tolist())
display(df.info()) 
display(df.head())
display(df.isnull().sum().sort_values(ascending=False).head(10))

(155507, 19)
['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC', 'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT', 'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD', 'Y_COORD_CD', 'Latitude', 'Longitude', 'New Georeferenced Column']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155507 entries, 0 to 155506
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ARREST_KEY                155507 non-null  int64
 1   ARREST_DATE               155507 non-null  datetime64[ns]
 2   PD_CD                     155478 non-null  float64
 3   PD_DESC                   155404 non-null  object
 4   KY_CD                     155404 non-null  float64
 5   OFNS_DESC                 155404 non-null  object
 6   LAW_CODE                  155507 non-null  object
 7   LAW_CAT_CD                154114 non-null  object
 8   ARREST_BORO               155507 non-null  object
 9   ARREST_PRECINCT           155507 non-null  int64
 10  JURISDICTION_CODE         155507 non-null  int64
 11  AGE_GROUP                 155507 non-null  object
 12  PERP_SEX                  155507 non-null  object
 13  PERP_RACE                 155507 non-null  object
 14  X_COORD_CD                155507 non-null  int64
 15  Y_COORD_CD                155507 non-null  int64
 16  Latitude                  155507 non-null  float64
 17  Longitude                 155507 non-null  float64
 18  New Georeferenced Column  155507 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(5), object(9)
memory usage: 22.5+ MB

None

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,K,83,0,25-44,M,WHITE HISPANIC,1002212,193214,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,104,0,25-44,M,WHITE HISPANIC,1012082,206579,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200507,F,B,52,0,25-44,M,WHITE HISPANIC,1017440,256046,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,0,25-44,F,BLACK,936722,172119,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,K,72,0,25-44,M,WHITE HISPANIC,981292,171046,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)

LAW_CAT_CD         1393
PD_DESC             103
OFNS_DESC           103
KY_CD               103
PD_CD                29
ARREST_DATE           0
ARREST_KEY            0
LAW_CODE              0
ARREST_BORO           0
ARREST_PRECINCT       0
dtype: int64

In [40]:
# check uniqueness
df['ARREST_KEY'].is_unique
df.duplicated(subset='ARREST_KEY').sum()

np.int64(0)

In [41]:
df = df.drop(columns=['PD_CD', 'KY_CD', 'LAW_CODE', 'JURISDICTION_CODE', 'X_COORD_CD', 'Y_COORD_CD'])
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,K,83,25-44,M,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,Q,104,25-44,M,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,F,B,52,25-44,M,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,S,121,25-44,F,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,K,72,25-44,M,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,F,Q,104,18-24,M,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,M,B,40,25-44,M,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,F,K,79,45-64,M,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,F,Q,105,25-44,M,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,F,M,18,45-64,M,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [42]:
df = df.replace({'ARREST_BORO': {'B': 'BRONX', 'K': 'BROOKLYN', 'M': 'MANHATTAN', 'Q': 'QUEENS', 'S': 'STATEN ISLAND'}})
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,BROOKLYN,83,25-44,M,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,QUEENS,104,25-44,M,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,F,BRONX,52,25-44,M,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,STATEN ISLAND,121,25-44,F,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,M,BROOKLYN,72,25-44,M,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,F,QUEENS,104,18-24,M,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,M,BRONX,40,25-44,M,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,F,BROOKLYN,79,45-64,M,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,F,QUEENS,105,25-44,M,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,F,MANHATTAN,18,45-64,M,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [43]:
df = df.replace({'LAW_CAT_CD': {'F': 'FELONY', 'M': 'MISDEMEANOR', 'V': 'VIOLATION','I': 'INFRACTION'}})
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,BROOKLYN,83,25-44,M,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,QUEENS,104,25-44,M,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,FELONY,BRONX,52,25-44,M,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,STATEN ISLAND,121,25-44,F,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,BROOKLYN,72,25-44,M,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,FELONY,QUEENS,104,18-24,M,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,MISDEMEANOR,BRONX,40,25-44,M,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,FELONY,BROOKLYN,79,45-64,M,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,FELONY,QUEENS,105,25-44,M,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,FELONY,MANHATTAN,18,45-64,M,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [44]:
df = df.replace({'PERP_SEX': {'F': 'FEMALE', 'M': 'MALE', 'U': 'UNKNOWN'}})
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,BROOKLYN,83,25-44,MALE,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,QUEENS,104,25-44,MALE,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,FELONY,BRONX,52,25-44,MALE,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,STATEN ISLAND,121,25-44,FEMALE,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,ASSAULT 3,ASSAULT 3 & RELATED OFFENSES,MISDEMEANOR,BROOKLYN,72,25-44,MALE,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,FELONY,QUEENS,104,18-24,MALE,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,MISDEMEANOR,BRONX,40,25-44,MALE,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",FELONY ASSAULT,FELONY,BROOKLYN,79,45-64,MALE,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,FELONY,QUEENS,105,25-44,MALE,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,FELONY,MANHATTAN,18,45-64,MALE,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [45]:
df['OFNS_DESC'] = df['OFNS_DESC'].str.replace(r".*assault.*", "ASSAULT", case=False, regex=True)
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,BROOKLYN,83,25-44,MALE,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,QUEENS,104,25-44,MALE,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",ASSAULT,FELONY,BRONX,52,25-44,MALE,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,STATEN ISLAND,121,25-44,FEMALE,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,BROOKLYN,72,25-44,MALE,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,FELONY,QUEENS,104,18-24,MALE,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,MISDEMEANOR,BRONX,40,25-44,MALE,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",ASSAULT,FELONY,BROOKLYN,79,45-64,MALE,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,FELONY,QUEENS,105,25-44,MALE,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,FELONY,MANHATTAN,18,45-64,MALE,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [46]:
df['OFNS_DESC'] = df['OFNS_DESC'].str.replace("AGRICULTURE & MRKTS LAW-UNCLASSIFIED", "ANIMAL CRUELTY")

In [47]:
df.fillna('UNKNOWN', inplace=True)
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column
0,222488045,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,BROOKLYN,83,25-44,MALE,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005)
1,222488087,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,QUEENS,104,25-44,MALE,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006)
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",ASSAULT,FELONY,BRONX,52,25-44,MALE,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004)
3,222488113,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,STATEN ISLAND,121,25-44,FEMALE,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007)
4,222500383,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,BROOKLYN,72,25-44,MALE,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,FELONY,QUEENS,104,18-24,MALE,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007)
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,MISDEMEANOR,BRONX,40,25-44,MALE,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006)
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",ASSAULT,FELONY,BROOKLYN,79,45-64,MALE,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002)
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,FELONY,QUEENS,105,25-44,MALE,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034)
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,FELONY,MANHATTAN,18,45-64,MALE,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)

In [48]:
months_order = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]

df['MONTH'] = df['ARREST_DATE'].dt.month_name()
df

,ARREST_KEY,ARREST_DATE,PD_DESC,OFNS_DESC,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,New Georeferenced Column,MONTH
0,222488045,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,BROOKLYN,83,25-44,MALE,WHITE HISPANIC,40.696995,-73.935225,POINT (-73.93522525599997 40.69699455600005),January
1,222488087,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,QUEENS,104,25-44,MALE,WHITE HISPANIC,40.733653,-73.899576,POINT (-73.89957593999998 40.73365273100006),January
2,222487994,2021-01-01,"ASSAULT 2,1,UNCLASSIFIED",ASSAULT,FELONY,BRONX,52,25-44,MALE,WHITE HISPANIC,40.869407,-73.879998,POINT (-73.87999831299999 40.86940749200004),January
3,222488113,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,STATEN ISLAND,121,25-44,FEMALE,BLACK,40.638984,-74.171252,POINT (-74.17125230499995 40.63898417600007),January
4,222500383,2021-01-01,ASSAULT 3,ASSAULT,MISDEMEANOR,BROOKLYN,72,25-44,MALE,WHITE HISPANIC,40.636166,-74.010659,POINT (-74.01065912499998 40.636166049000046),January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,238474826,2021-12-31,"FORGERY,ETC.,UNCLASSIFIED-FELO",FORGERY,FELONY,QUEENS,104,18-24,MALE,WHITE HISPANIC,40.708689,-73.899949,POINT (-73.89994899199996 40.70868945500007),December
155503,238489811,2021-12-31,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",CRIMINAL MISCHIEF & RELATED OF,MISDEMEANOR,BRONX,40,25-44,MALE,WHITE HISPANIC,40.819127,-73.917392,POINT (-73.91739228599994 40.81912706800006),December
155504,238471404,2021-12-31,"ASSAULT 2,1,UNCLASSIFIED",ASSAULT,FELONY,BROOKLYN,79,45-64,MALE,BLACK,40.695549,-73.947787,POINT (-73.94778709999997 40.69554895700002),December
155505,238486294,2021-12-31,CRIMINAL CONTEMPT 1,MISCELLANEOUS PENAL LAW,FELONY,QUEENS,105,25-44,MALE,ASIAN / PACIFIC ISLANDER,40.726293,-73.734761,POINT (-73.73476084899994 40.726293088000034),December
155506,238481259,2021-12-31,"LARCENY,GRAND FROM OPEN AREAS, UNATTENDED",GRAND LARCENY,FELONY,MANHATTAN,18,45-64,MALE,BLACK,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074),December

In [49]:
df.to_csv("../data/clean_nypd_arrests_data.csv", index=False)

In [63]:
import geopandas as gpd
import pandas as pd

# Load neighborhoods shapefile
ntas = gpd.read_file("../data/shape_files/geo_export_704a8741-320c-48d2-8925-e0e95022996b.shp").to_crs("EPSG:4326")

# Load arrests CSV and convert to GeoDataFrame
arrests = pd.read_csv("../data/clean_nypd_arrests_data.csv")
arrests_gdf = gpd.GeoDataFrame(
    arrests,
    geometry=gpd.points_from_xy(arrests["Longitude"], arrests["Latitude"]),
    crs="EPSG:4326"
)

# Spatial join: assign arrests to neighborhoods
joined = gpd.sjoin(arrests_gdf, ntas, how="inner", predicate="within")

# # Aggregate arrests per neighborhood
# neighborhood_counts = joined.groupby("ntaname").size().reset_index(name="Arrest_Count")

# # Merge counts back to polygons
# ntas_counts = ntas.merge(neighborhood_counts, left_on="ntaname", right_on="ntaname", how="left")

# Save cleaned file for Tableau
ntas_counts.to_file("../data/neighborhoods_with_arrests.shp")

/tmp/ipykernel_24001/1494504257.py:25: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  ntas_counts.to_file("../data/neighborhoods_with_arrests.shp")
/home/justin/anaconda3/lib/python3.13/site-packages/pyogrio/raw.py:723: RuntimeWarning: Normalized/laundered field name: 'Arrest_Count' to 'Arrest_Cou'
  ogr_write(